global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'honestly-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 5s

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']  # Neo4j Prometheus endpoint (if enabled)


